`get_field_data` produce compile error
this function `get_field_data` produce compile error because you match on a non-empty list with an empty list
```
== Compilation error in file lib/report.ex ==
** (FunctionClauseError) no function clause matching in TypedStruct.get_field_data/1    
    
    The following arguments were given to TypedStruct.get_field_data/1:
    
        # 1
        {:field, [line: 7], [:type, {:report_type, [line: 7], nil}, [required?: true, default: :refactoring]]}
    
    lib/typed_struct.ex:42: TypedStruct.get_field_data/1
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    expanding macro: TypedStruct.typedstruct/1
    lib/report.ex:6: Report (module)
```
When I passed `meta` variable inside `[]` it worked fine.